general:
  acnet: jpeg
  benet: jpeg
  crnet: jpeg
  ppnet: bicubicpp

  log_dir: 'logs_infer_test'
  load_model_dir: 'sparams_new'


  train_dirs: ['/mnt/datasets/DIV2K_train_HR_bmp/']
  val_dirs: ['/home/ubuntu/data/datasets/DIV2K_valid_HR_bmp/']
  test_dirs: ['/mnt/datasets/set14/']

  crop_size: 0
  batch_size: 1
  interpolation: bicubic
  antialias: True
  num_workers: 16
  scale_factor: 2
  post_only: False
  scale: 2
  color_channels: 3



acnet:
  name: jpeg
  num_levels: 12

benet:
  name: jpeg
  m: 10

crnet:
  name: tad

ppnet:
  name: bicubicpp