general:
  acnet: jpeg
  benet: jpeg
  crnet: jpeg
  pnet: desr

  log_dir: 'logs'
  model_dir: 'params'

  train_dirs: ['/mnt/datasets/coco/unlabeled2017/']
  val_dirs: ['/mnt/datasets/set14/']
  test_dirs: ['/mnt/datasets/set14/']

  crop_size: 128
  batch_size: 16
  lr: 0.0001
  epochs: 2000
  interpolation: bicubic
  antialias: True
  num_workers: 16
  scale_factor: 2

  scale: 2
  summary_iters: 100
  color_channels: 3

acnet:
  train: True
  name: jpeg
  num_levels: 12
  save: True

benet:
  train: True
  name: jpeg
  m: 10
  save: True

crnet:
  train: False
  name: tad
  save: False

ppnet:
  train: True
  name: bicubicpp
  save: True